default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: 1
  host: localhost

development:
  <<: *default
  database: tutu_development

test:
  <<: *default
  database: tutu_test

